posix_curdir <- '.'
posix_pardir <- '..'
posix_extsep <- '.'
posix_sep <- '/'
posix_pathsep <- ':'
posix_defpath <- ':/bin:/usr/bin'
posix_altsep <- NULL
posix_devnull <- '/dev/null'
posix_supports_unicode_filenames <- FALSE
